### ISSUE TITLE
disconnect after a minute (guest), and a few interesting things :)

### ISSUE THREAD

**Issue by udi111** [endtwist/AjaxIM#7] opened 2010-03-10 17:51 UTC
1.) i'm testing the guest mode (latest) on my server and it seems to work but in a conversation, the client who sends the last message, will be disconnected after a minute.
if no messages are sent, the server keeps the client logged in.
as i see the same happens on ajaxim.com.
2.) i opened ajaxim.com in firefox, it reports 12 friends, the same time in safari this number is 4 only.
3.) the client itself is listed on the friends list - not nice :)
4.) if the sent message text is a number, the received message is "{message}". in this case, the recipient will be logged out, not the sender :))))
5.) feature req: i'd like to see a "pick a username" field in guest mode :)

**Comment by endtwist** [comment] 2010-03-10 18:42
1) Can you give me the steps to reproduce this issue? I cannot reproduce it myself.
2) Can you give me the steps to reproduce this issue? I cannot reproduce it myself.
3) Yes, it is. There is nothing wrong with that, nor will that feature be removed.
4) I can confirm that this is a bug and it will be fixed.
5) Will be considered. No promises, however.

**Comment by udi111** [comment] 2010-03-10 19:19
1.) i open ajaxim.com in firefox and safari.
i send a message from safari to ff.
the message displays in ff, but after a minute it says that the saffari user signed off.
the same happens in the other direction, and the same with the latest version on my server.
2.) maybe this was a conflict because both ajaxim.com and my test page were open.
3.) who wants to send a message to himself? :)
5.) if this would be implemented, we could easily reproduce and discuss the bug above :)

**Comment by udi111** [comment] 2010-03-13 14:10
1.) i tested it from my other pc and i got the same result.
just open ajaxim.com and send a message to anybody, wait a minute and refresh the page, and wow you got a new session!

**Closed as completed** 2010-09-23 19:02 UTC
Labels: Confirmed Bug, Feature Request, Unconfirmed Bug
